server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://AILab:PaaS@127.0.0.1:8761/eureka/
  instance:
    hostname: biz-health-dev
    instance-id: biz-health-dev:biz-health-dev:8083
spring:
  application:
    name: biz-health-dev
