server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://AILab:PaaS@127.0.0.1:8761/eureka/
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
spring:
  application:
    name: aiclient-test