management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  cloud:
    gateway:
      routes:
        - id: jd
          uri: http://jd.com
          predicates:
            - Path=/jd
server:
  port: 8080