spring:
  application:
    name: api-gateway
server:
  port: 10019
eureka:
  client:
    serviceUrl:
      defaultZone: http://jbzm:zhengyiwoaini@localhost:10010/eureka,http://jbzm:zhengyiwoaini@localhost:10009/eureka
zuul:
  routes:
    api-a-url:
      path: /api-a/**
      serviceId: eureka-client-a
    api-b-url:
      path: /api-b/**
      serviceId: eureka-client-b