spring:
  application:
    name: api-gateway
server:
  port: 10019
eureka:
  client:
    serviceUrl:
      defaultZone: http://server1:10009/eureka,http://server2:10009/eureka
zuul:
  routes:
    eureka-client-a: /api-a/**
    eureka-client-b: /api-b/**