eureka:
  instance:
    hostname: eureka-server
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 3000
    response-cache-update-interval-ms: 3000
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://AILab:PaaS@127.0.0.1:8761/eureka/
spring:
  application:
    name: eureka-server
  profiles:
    active: master
  security:
    user:
      name: AILab
      password: PaaS
server:
  port: 8761
management:
  endpoints:
    web:
      exposure:
        exclude: '*'