spring:
  application:
    name: ${artifactId}
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  profiles:
    active: local
management:
  endpoints:
    web:
      exposure:
        include: "*"
