spring:
  application:
    name: gateway
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  profiles:
    active: local
management:
  endpoints:
    web:
      exposure:
        include: "*"
ribbon:
  ReadTimeout : 300000
  ConnectTimeout : 300000