server:
  port: 8760
  error:
    include-stacktrace: always
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      #gateway
      routes:
        - id: create_task
          uri: lb://createtask-service
          predicates:
            - Path=/api/create/**
          filters:
            - StripPrefix=2
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
        - id: vegas-admin-service
          uri: lb://vegas-admin-service
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=2
        - id: vegas-platform
          uri: lb://vegas-platform
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: jbzm-test
          uri: lb://jbzm-test
          predicates:
            - Path=/jbzm/**
          filters:
            - StripPrefix=1
        - id: jbzm-log
          uri: lb://jbzm-log
          predicates:
            - Path=/log/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

#custom
gateway:
  filter:
    ignore-uri:
      - /api/vegas/sleep/test
      - /api/vegas/accept/texture
      - /api/auth/**
      - /jbzm/**
      - /log/**
