server:
  port: 11130
spring:
  application:
    name: jwt-test
  datasource:
    username: root
    password: Shuaizheng1995!!
    url: jdbc:mysql://192.168.100.161:3306/jwt_test?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://jbzm:jbzm521@localhost:11010/eureka
    registry-fetch-interval-seconds: 10

app:
  jwtSecret: zhengyiwoaini
  jwtExpirationInMs: 604800000


