spring:
  application:
    name: eureka-consumer-feign
server:
  port: 10014
eureka:
  client:
    service-url:
      defaultZone: http://AILab:PaaS@127.0.0.1:8761/eureka/
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
