eureka:
  instance:
    hostname: vegas-eureka-master
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000
    response-cache-update-interval-ms: 3000
server:
  port: 8761
spring:
  application:
    name: vegas-eureka-server
  profiles:
    active: master
  security:
    user:
      name: admin
      password: admin
