spring:
  application:
    name: eureka-server
server:
  port: 10010
# eureka配置
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:10009/eureka
  server:
    enable-self-preservation: false

