spring:
  application:
    name: eureka-server   #服务名称
server:
  port: 10010   #制定端口号
# eureka配置
eureka:
  instance:
    hostname: localhost   #标识注册的ip
  client:
    serviceUrl:
      defaultZone: http://jbzm:zhengyiwoaini@localhost:10009/eureka    #向注册中心注册的节点
  server:
    enable-self-preservation: false   #禁止使用安全检查