
server:
  port: 10010   #制定端口号
# eureka配置
eureka:
  instance:
    hostname: eureka1   #标识注册的ip
  client:
    serviceUrl:
      defaultZone: http://localhost:10009/eureka    #向注册中心注册的节点
  server:
    enable-self-preservation: false   #禁止使用安全检查