
server:
  port: 10009   #制定端口号
# eureka配置
eureka:
  instance:
    hostname: server1   #标识注册的ip
  client:
    serviceUrl:
      defaultZone: http://192.168.100.161:10009/eureka    #向注册中心注册的节点
  server:
    enable-self-preservation: false   #禁止使用安全检查