spring:
  application:
    name: eureka-server
server:
  port: 10009
# eureka配置
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:10010/eureka
  server:
    enable-self-preservation: false

