server:
  port: 10010
# eureka配置
eureka:
  instance:
    hostname: server2lol
  client:
    serviceUrl:
      defaultZone: http://39.107.112.223:8768/eureka/
  server:
    enable-self-preservation: false


